### ISSUE TITLE
Emotion roulette interval

### ISSUE THREAD

**Issue by Quipex** [JuniperBot/JuniperBot#144]
Would be a nice feature to add an option of minimal messages interval between adding a react. 
Now, sometimes random triggers consequently and bot spams with emotes. 

Kinda rough solution is to create a Map<ChannelId, HowManyMessagesHasntBeenReacted> that is updated every time a new message arrives. If that map value is bigger than the interval in settings, the bot can add a reaction, otherwise it cannot. Of course, after adding a reaction the counter gets reset.

**Comment by GoldRenard** [comment]
Good idea. I'll implement that.

**Comment by GoldRenard** [comment]
Implemented in 6.7
